### PR TITLE
Fix for small bugs in the cropping function

### PR DESCRIPTION
**Pull request by davide84**
Hallo, I think I found a couple of small bugs in Pipeline.py crop() function; details are provided in the commit comments where applicable.

### CODE REVIEW

**Comment by malago86** [comment]
Hi Davide, thanks for your input!

I am almost sure that the x,y indexes for the coordinates are correct. MCGPU takes coordinates in a different way than the FBP reconstruction software, so those indexes need to be interchanged. Did you try to run the pipeline after your change? Did you have issues with the reconstruction before?

As for the .gz added to the .mhd pointer to the filename, I can that parameter `CompressedData = True` and use the .raw.gz if it is True, otherwise just use .raw. It seems like you are loading the phantoms on a different software, I did not account for that case! It works well with ImageJ with and without the .gz...

The rest of the pipeline does not use .raw.gz since the compression is not really making a big difference for the DM and DBT images and it adds compressing/decompressing overload.

One question for you, using `CompressedData = True` makes it compatible with 3D-Slicer and the .raw.gz filename?

**Comment by davide84** [comment]
Hi!

Yes, using .raw.gz and `CompressedData = True` makes the data readable from Slicer. If there is a mismatch between the boolean value and the extension, Slicer will show a thin slab with noisy pixels instead of the phantom.

I trust you on the coordinates... until today the cropping seemed to be not working for me, so I never used until now. I now realize that the raw file was fine and only my visual inspection was broken.

I am running the pipeline multiple times, with different breast size/thickness and density. But I usually separate the phantom generation script from the projection script, so the pipelines are different instances and I think those inverted values were never used in my case. I will double check.

**Comment by davide84** [comment]
Hi! I edited my commits, removing the index inversion and adding some other small changes that I made during my work with the pipeline. They are all Non-Functional Changes, except the fix for the compression flag in the crop.mhd file. I hope they are helpful.

All the changes have been re-tested by compressing existing phantoms and opening the compressed files with 3DSlicer.

**Comment by malago86** [comment]
This is great! Thanks @davide84, I have looked at your commits and will probably accept them. Thanks!

**Comment by malago86** [comment]
This has been now implemented on the code. Thanks again.

**Pull request closed without merging**
